@host = http://localhost:5167/api/v1
@productId = 77777777-7777-7777-7777-777777777777
GET {{host}}/products
Accept: application/json

###
GET {{host}}/products/{{productId}}
Accept: application/json

###
POST {{host}}/products
Accept: application/json

{

}